server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/jobmatcher_db
    username: postgres
    password: walid
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

jwt:
  secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970